[package]
name = "fta"
version = "0.1.0"
edition = "2024"

[dependencies]
atrium-api = "0.25"
bsky-sdk = "0.1"
chrono = "0.4"
clap = { version = "4.5", features = ["derive", "unicode"] }
dirs = "6.0"
gemini-rust = "1.7"
serde_json = "1.0"
tokio = { version = "1.30", features = ["full"] }